namespace RazorDbManager.Core;

/// <summary>Identifies a schema-qualified database object.</summary>
public readonly record struct DbObjectName
{
    /// <summary>Initializes a schema-qualified object name.</summary>
    /// <param name="schema">The schema name.</param>
    /// <param name="name">The unqualified object name.</param>
    public DbObjectName(string schema, string name)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(schema);
        ArgumentException.ThrowIfNullOrWhiteSpace(name);
        Schema = schema;
        Name = name;
    }

    /// <summary>Gets the schema name.</summary>
    public string Schema { get; }
    /// <summary>Gets the unqualified object name.</summary>
    public string Name { get; }

    /// <inheritdoc />
    public override string ToString() => $"{Schema}.{Name}";
}

/// <summary>Classifies an object displayed by the database browser.</summary>
public enum DbObjectKind
{
    /// <summary>A base table.</summary>
    Table,
    /// <summary>A view.</summary>
    View,
}

/// <summary>Describes the semantic family of a database column.</summary>
public enum DbDataKind
{
    /// <summary>The provider could not map the type to a standard family.</summary>
    ProviderSpecific,
    /// <summary>A signed whole number.</summary>
    SignedInteger,
    /// <summary>An unsigned whole number.</summary>
    UnsignedInteger,
    /// <summary>An exact decimal number.</summary>
    Decimal,
    /// <summary>An approximate floating-point number.</summary>
    FloatingPoint,
    /// <summary>A Boolean or Boolean-compatible value.</summary>
    Boolean,
    /// <summary>Unicode or provider-encoded text.</summary>
    Text,
    /// <summary>Binary data.</summary>
    Binary,
    /// <summary>A date without a time.</summary>
    Date,
    /// <summary>A time without a date.</summary>
    Time,
    /// <summary>A date and time without an implied time zone.</summary>
    DateTime,
    /// <summary>A date and time representing an instant.</summary>
    Timestamp,
    /// <summary>A JSON document.</summary>
    Json,
    /// <summary>An enumeration value.</summary>
    Enum,
    /// <summary>A set of enumeration values.</summary>
    Set,
    /// <summary>A fixed-width bit string.</summary>
    BitString,
    /// <summary>A spatial value.</summary>
    Geometry,
    /// <summary>A globally unique identifier.</summary>
    Guid,
}

/// <summary>Describes a provider data type without losing its original declaration.</summary>
/// <param name="ProviderTypeName">The canonical provider type declaration.</param>
/// <param name="Kind">The provider-neutral type family.</param>
/// <param name="IsUnsigned">Whether numeric values are unsigned.</param>
/// <param name="Length">The declared character, binary, or bit length.</param>
/// <param name="Precision">The declared numeric precision.</param>
/// <param name="Scale">The declared numeric scale.</param>
/// <param name="AllowedValues">The values allowed by an enum or set declaration.</param>
public sealed record DbTypeDescriptor(
    string ProviderTypeName,
    DbDataKind Kind,
    bool IsUnsigned = false,
    long? Length = null,
    int? Precision = null,
    int? Scale = null,
    IReadOnlyList<string>? AllowedValues = null);

/// <summary>Describes one result or table column.</summary>
/// <param name="Name">The column name.</param>
/// <param name="Ordinal">The zero-based ordinal.</param>
/// <param name="Type">The database type.</param>
/// <param name="IsNullable">Whether the column accepts null.</param>
/// <param name="DefaultSql">The provider-reported default expression, for display only.</param>
/// <param name="IsGenerated">Whether the value is generated by the database.</param>
/// <param name="IsAutoIncrement">Whether inserts generate a numeric value.</param>
/// <param name="Comment">The optional database comment.</param>
/// <param name="CharacterSet">The optional character set.</param>
/// <param name="Collation">The optional collation.</param>
public sealed record DbColumnMetadata(
    string Name,
    int Ordinal,
    DbTypeDescriptor Type,
    bool IsNullable,
    string? DefaultSql = null,
    bool IsGenerated = false,
    bool IsAutoIncrement = false,
    string? Comment = null,
    string? CharacterSet = null,
    string? Collation = null);

/// <summary>Classifies a candidate row-identity key.</summary>
public enum DbKeyKind
{
    /// <summary>A primary key.</summary>
    Primary,
    /// <summary>A unique key.</summary>
    Unique,
}

/// <summary>Describes a primary or unique key.</summary>
/// <param name="Name">The provider key name.</param>
/// <param name="Kind">The key classification.</param>
/// <param name="Columns">Ordered key-column names.</param>
/// <param name="IsUsableForRowIdentity">Whether all key columns are non-nullable and can safely identify one row.</param>
public sealed record DbKeyMetadata(
    string Name,
    DbKeyKind Kind,
    IReadOnlyList<string> Columns,
    bool IsUsableForRowIdentity);

/// <summary>Describes one indexed column.</summary>
/// <param name="Name">The column name.</param>
/// <param name="Descending">Whether the key is descending.</param>
/// <param name="PrefixLength">An optional provider-supported prefix length.</param>
public sealed record DbIndexColumn(string Name, bool Descending = false, int? PrefixLength = null);

/// <summary>Describes a database index.</summary>
/// <param name="Name">The index name.</param>
/// <param name="Columns">Ordered index columns.</param>
/// <param name="IsUnique">Whether values must be unique.</param>
/// <param name="IsPrimary">Whether this is the primary index.</param>
/// <param name="Method">The provider-reported indexing method.</param>
public sealed record DbIndexMetadata(
    string Name,
    IReadOnlyList<DbIndexColumn> Columns,
    bool IsUnique,
    bool IsPrimary = false,
    string? Method = null);

/// <summary>Specifies behavior when a referenced row is deleted or updated.</summary>
public enum DbReferentialAction
{
    /// <summary>Use the database default.</summary>
    NoAction,
    /// <summary>Reject the parent change while dependents exist.</summary>
    Restrict,
    /// <summary>Propagate the parent change.</summary>
    Cascade,
    /// <summary>Set dependent values to null.</summary>
    SetNull,
    /// <summary>Set dependent values to their defaults.</summary>
    SetDefault,
}

/// <summary>Describes a foreign-key relationship.</summary>
/// <param name="Name">The constraint name.</param>
/// <param name="Columns">Ordered local columns.</param>
/// <param name="ReferencedTable">The referenced table.</param>
/// <param name="ReferencedColumns">Ordered referenced columns.</param>
/// <param name="OnDelete">The delete action.</param>
/// <param name="OnUpdate">The update action.</param>
public sealed record DbForeignKeyMetadata(
    string Name,
    IReadOnlyList<string> Columns,
    DbObjectName ReferencedTable,
    IReadOnlyList<string> ReferencedColumns,
    DbReferentialAction OnDelete,
    DbReferentialAction OnUpdate);

/// <summary>Summarizes an object for the navigation tree.</summary>
/// <param name="Name">The object name.</param>
/// <param name="Kind">The object kind.</param>
/// <param name="EstimatedRowCount">An optional approximate row count.</param>
/// <param name="Comment">An optional comment.</param>
public sealed record DbObjectSummary(
    DbObjectName Name,
    DbObjectKind Kind,
    long? EstimatedRowCount = null,
    string? Comment = null);

/// <summary>Describes the objects visible within one schema.</summary>
/// <param name="Name">The schema name.</param>
/// <param name="Objects">The visible tables and views.</param>
public sealed record DbSchemaMetadata(string Name, IReadOnlyList<DbObjectSummary> Objects);

/// <summary>Describes a registered database and its visible schemas.</summary>
/// <param name="DatabaseId">The registration identifier.</param>
/// <param name="ProductName">The provider-reported database product.</param>
/// <param name="ProductVersion">The provider-reported product version.</param>
/// <param name="DefaultSchema">The inferred default schema.</param>
/// <param name="Schemas">Visible schema summaries.</param>
/// <param name="CapturedAt">The instant at which metadata was read.</param>
/// <param name="EffectiveCapabilities">Capabilities supported by both registration and server credentials.</param>
public sealed record DatabaseMetadata(
    string DatabaseId,
    string ProductName,
    string ProductVersion,
    string? DefaultSchema,
    IReadOnlyList<DbSchemaMetadata> Schemas,
    DateTimeOffset CapturedAt,
    RazorDbCapability EffectiveCapabilities);

/// <summary>Describes an editable table or readable view in detail.</summary>
/// <param name="Name">The object name.</param>
/// <param name="Kind">The object kind.</param>
/// <param name="Columns">Ordered columns.</param>
/// <param name="Keys">Primary and unique keys.</param>
/// <param name="Indexes">All indexes.</param>
/// <param name="ForeignKeys">Foreign keys declared by the object.</param>
/// <param name="RowIdentityKey">The key selected for safe row mutation, or null when none exists.</param>
/// <param name="SchemaFingerprint">An opaque fingerprint that changes with the relevant schema.</param>
/// <param name="Engine">An optional storage engine.</param>
/// <param name="Collation">An optional object collation.</param>
/// <param name="Comment">An optional comment.</param>
public sealed record DbTableMetadata(
    DbObjectName Name,
    DbObjectKind Kind,
    IReadOnlyList<DbColumnMetadata> Columns,
    IReadOnlyList<DbKeyMetadata> Keys,
    IReadOnlyList<DbIndexMetadata> Indexes,
    IReadOnlyList<DbForeignKeyMetadata> ForeignKeys,
    DbKeyMetadata? RowIdentityKey,
    string SchemaFingerprint,
    string? Engine = null,
    string? Collation = null,
    string? Comment = null)
{
    /// <summary>Gets whether this object can be safely updated or deleted one row at a time.</summary>
    public bool SupportsRowMutation => Kind == DbObjectKind.Table && RowIdentityKey is not null;
}

/// <summary>Requests current metadata for a registered database.</summary>
/// <param name="DatabaseId">The registration identifier.</param>
/// <param name="Refresh">Whether a provider should bypass its metadata cache.</param>
public sealed record MetadataRequest(string DatabaseId, bool Refresh = false);
